import type { BookmarkNode } from './types'
import { nodeToAttrString } from './mapper'

export default function generateBookmarkHtml(
  nodes: Record<string, BookmarkNode>,
): string {
  let html = '<!DOCTYPE NETSCAPE-Bookmark-file-1>\n'
  html += '<!-- Generated by NEXA - DO NOT EDIT! -->\n'
  html += '<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">\n'
  html += '<TITLE>Bookmarks</TITLE>\n'
  html += '<H1>Bookmarks</H1>\n'
  html += '<DL><p>\n'

  const allNodes = Object.values(nodes)

  function renderNodes(parentId: string | null, indent: number) {
    const indentStr = '    '.repeat(indent)
    const children = allNodes.filter((n) => n.parentId === parentId)

    for (const node of children) {
      const attrs = nodeToAttrString(node)

      if (node.type === 'folder') {
        html += `${indentStr}<DT><H3${attrs}>${node.title}</H3>\n`
        html += `${indentStr}<DL><p>\n`
        renderNodes(node.id, indent + 1)
        html += `${indentStr}</DL><p>\n`
      } else {
        html += `${indentStr}<DT><A${attrs}>${node.title}</A>\n`
      }
    }
  }

  renderNodes(null, 1)
  html += '</DL><p>\n'
  return html
}
