import { elementToNodeData, nodeToAttrString } from './mapper'
import type { BookmarkNodes } from './types'

export const BookmarkHTML = {
  parse(html: string): BookmarkNodes {
    const parser = new DOMParser()
    const doc = parser.parseFromString(html, 'text/html')
    const nodes: BookmarkNodes = {}

    const rootDl = doc.querySelector('dl')
    if (!rootDl) return nodes

    const parseDl = (dl: HTMLElement, parentId: string | null) => {
      const items = dl.querySelectorAll(':scope > dt')

      for (const dt of Array.from(items)) {
        const h3 = dt.querySelector(':scope > h3')
        const a = dt.querySelector(':scope > a')

        if (h3) {
          const folderData = elementToNodeData(h3 as HTMLElement, {
            type: 'folder',
            title: h3.textContent || '',
            parentId
          })
          nodes[folderData.id] = folderData

          const subDl = dt.querySelector(':scope > dl')
          if (subDl) {
            parseDl(subDl as HTMLElement, folderData.id)
          }
        } else if (a) {
          const linkData = elementToNodeData(a as HTMLElement, {
            type: 'link',
            title: a.textContent || '',
            parentId
          })
          nodes[linkData.id] = linkData
        }
      }
    }

    parseDl(rootDl, null)
    return nodes
  },

  generate(
    nodes: BookmarkNodes,
  ): string {
    let html = '<!DOCTYPE NETSCAPE-Bookmark-file-1>\n'
    html += '<!-- Generated by NEXA - DO NOT EDIT! -->\n'
    html += '<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">\n'
    html += '<TITLE>Bookmarks</TITLE>\n'
    html += '<H1>Bookmarks</H1>\n'
    html += '<DL><p>\n'

    const allNodes = Object.values(nodes)

    const generateNode = (parentId: string | null, indent: number) => {
      const indentStr = '    '.repeat(indent)
      const children = allNodes.filter((n) => n.parentId === parentId)

      for (const node of children) {
        const attrs = nodeToAttrString(node)

        if (node.type === 'folder') {
          html += `${indentStr}<DT><H3${attrs}>${node.title}</H3>\n`
          html += `${indentStr}<DL><p>\n`
          generateNode(node.id, indent + 1)
          html += `${indentStr}</DL><p>\n`
        } else {
          html += `${indentStr}<DT><A${attrs}>${node.title}</A>\n`
        }
      }
    }

    generateNode(null, 1)
    html += '</DL><p>\n'
    return html
  }
}